# Generated by Django 4.1.1 on 2022-11-26 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="userDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_no", models.CharField(max_length=12)),
                (
                    "programme",
                    models.CharField(
                        choices=[
                            ("BT", "BTech"),
                            ("MT", "MTech"),
                            ("MU", "Medical UG"),
                            ("MP", "Medical PG"),
                        ],
                        max_length=12,
                    ),
                ),
                ("course", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=2
                    ),
                ),
                ("avatar", models.ImageField(blank=True, upload_to="avatar")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("G", "General"),
                            ("SC", "SC"),
                            ("ST", "ST"),
                            ("OBC", "Other backward Classes"),
                            ("EWS", "Economically Weaker Section"),
                        ],
                        max_length=3,
                    ),
                ),
                ("income", models.IntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["user"],},
        ),
    ]
