# Generated by Django 4.1.1 on 2022-12-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userdetails_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="programme",
            field=models.CharField(
                choices=[
                    ("BT", "BTech"),
                    ("BR", "BArch"),
                    ("DI", "Diploma"),
                    ("O", "Others"),
                ],
                max_length=12,
            ),
        ),
    ]
