# Generated by Django 4.1.1 on 2022-12-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userdetails_programme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetails",
            name="course",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
