# Generated by Django 4.1.1 on 2022-12-08 19:36

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("scholarship", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="category_elig",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("G", "General"),
                    ("SC", "SC"),
                    ("ST", "ST"),
                    ("OBC", "Other backward Classes"),
                    ("EWS", "Economically Weaker Section"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="gender_elig",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("M", "Male"), ("F", "Female")], max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="program_elig",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("BT", "BTech"),
                    ("BR", "BArch"),
                    ("DI", "Diploma"),
                    ("O", "Others"),
                ],
                max_length=12,
            ),
        ),
    ]
