# Generated by Django 4.1.1 on 2022-12-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarship", "0003_alter_scholarship_category_elig_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scholarship",
            old_name="category_elig",
            new_name="category_eligibility",
        ),
        migrations.RenameField(
            model_name="scholarship",
            old_name="gender_elig",
            new_name="gendereligibility",
        ),
        migrations.RenameField(
            model_name="scholarship",
            old_name="program_elig",
            new_name="program_eligibility",
        ),
    ]
