# Generated by Django 4.1.1 on 2022-12-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "scholarship",
            "0004_rename_category_elig_scholarship_category_eligibility_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="scholarship",
            old_name="income_elig",
            new_name="income_eligibility",
        ),
    ]
