# Generated by Django 4.1.1 on 2022-12-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scholarship", "0005_rename_income_elig_scholarship_income_eligibility"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scholarship",
            old_name="gendereligibility",
            new_name="gender_eligibility",
        ),
    ]
