# Generated by Django 4.1.1 on 2022-12-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=50)),
                ("logo", models.ImageField(blank=True, upload_to="exam/logo")),
                ("details", models.TextField()),
                ("link", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("points", models.IntegerField()),
                (
                    "certificate",
                    models.ImageField(blank=True, upload_to="exam/certificate"),
                ),
                ("eligibility", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=50)),
                ("logo", models.ImageField(blank=True, upload_to="lecture/logo")),
                ("details", models.TextField()),
                ("link", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("points", models.IntegerField()),
                (
                    "certificate",
                    models.ImageField(blank=True, upload_to="lecture/certificate"),
                ),
                ("speaker", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("venue", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=50)),
                ("logo", models.ImageField(blank=True, upload_to="workshop/logo")),
                ("details", models.TextField()),
                ("link", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("points", models.IntegerField()),
                (
                    "certificate",
                    models.ImageField(blank=True, upload_to="workshop/certificate"),
                ),
            ],
        ),
    ]
