# Generated by Django 4.1.1 on 2022-12-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="certificate",
            field=models.FileField(blank=True, upload_to="exam/certificate"),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="certificate",
            field=models.FileField(blank=True, upload_to="lecture/certificate"),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="certificate",
            field=models.FileField(blank=True, upload_to="workshop/certificate"),
        ),
    ]
