# Generated by Django 4.1.1 on 2022-12-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_exam_certificate_alter_lecture_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam", name="url", field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="lecture", name="url", field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="workshop", name="url", field=models.URLField(blank=True),
        ),
    ]
